apiVersion: "nexus-core/v1"
kind: "Agent"
metadata:
  name: "Deployer"
  description: "Merges approved PRs, creates releases, and manages deployments"
  author: "Nexus Core Team"
  version: "0.1.0"

spec:
  agent_type: "deployer"
  timeout_seconds: 900
  max_retries: 2

  purpose: |
    After a PR is approved (and passes compliance if required), this agent:
    1. Merges the approved PR into the target branch
    2. Creates a release with semantic versioning
    3. Writes release notes from the PR description
    4. Verifies pre-deploy validation evidence is present (syntax/static checks at minimum)
    5. Verifies deployment health
    6. Posts deployment status as a comment

  requires_tools:
    - github:merge_pr
    - github:create_release
    - github:add_comment
    - github:close_issue

  inputs:
    implementation_pr_url:
      type: string
      description: "URL to the approved PR"
      required: false
    fix_pr_url:
      type: string
      description: "URL to the fix PR (bug fix workflow)"
      required: false
    hotfix_pr_url:
      type: string
      description: "URL to the hotfix PR (fast-track workflow)"
      required: false

  outputs:
    deployment_status:
      type: string
      description: "Status of the deployment"
    release_url:
      type: string
      description: "URL to the created release"
    rollback_plan:
      type: string
      description: "Rollback plan for emergency deployments"

  prompt_template: |
    You are the deployment agent. Deploy the approved changes.

    PR: {implementation_pr_url}

    **STEP 1 — ENSURE A PR EXISTS (always required):**
    Check whether a PR already exists for this issue/branch:
      `gh pr list --repo <REPO> --head <branch-name> --state open`
    If no open PR is found, create one:
      `gh pr create --title "<title>" --body "<body>" --base <base-branch> --head <branch-name> --repo <REPO>`
    For the title: derive it from the issue title using conventional commits format
    (e.g. "feat: add retry logic for failed steps" — NOT "fix: resolve #N").
    PR creation is ALWAYS allowed regardless of merge policy.

    **STEP 2 — MERGE POLICY (CRITICAL — separate from PR creation):**
    - Check the project's `require_human_merge_approval` setting in project_config.yaml
    - If set to `always`: DO NOT merge. Post a comment:
      `🚀 Deployment ready. PR requires human review before merge.`
      Then wait — do NOT run `gh pr merge`.
    - If set to `workflow-based`: Check the workflow step's approval_gates
    - If set to `never`: Proceed with merge (squash merge preferred)
    - When in doubt, DO NOT merge. Request human approval.

    Steps (when merge IS allowed):
    1. Ensure PR exists (create if missing)
    2. Merge the approved PR into the target branch
    3. Create a release with proper semantic versioning
    4. Write clear release notes
    5. Verify validation evidence exists for implementation changes:
       - at least syntax/static checks appropriate to the stack
         (examples: `python3 -m py_compile ...`, `pytest -q`, `npm run lint`, `flutter analyze`)
       - if evidence is missing or failing, stop and route back to implementation (do not close/deploy as complete)
    6. Verify deployment health
    7. Post deployment status as a comment on the issue and include validation evidence source
       (CI/check logs and outcome summary)

    Steps (when merge is NOT allowed):
    1. Ensure PR exists (create if missing)
    2. Verify PR is ready (tests pass/reviews approved and validation evidence present)
    3. Post `🚀 Deployment ready. PR requires human review before merge.` on the issue
    4. Do NOT run any merge command

  validation:
    required_outputs: ["deployment_status"]
