apiVersion: "nexus-core/v1"
kind: "Agent"
metadata:
  name: "deployer"
  description: "Merges approved PRs, creates releases, and manages deployments"
  author: "Nexus Core Team"
  version: "0.1.0"

spec:
  agent_type: "deployer"
  timeout_seconds: 900
  max_retries: 2

  purpose: |
    After a PR is approved (and passes compliance if required), this agent:
    1. Merges the approved PR into the target branch
    2. Creates a release with semantic versioning
    3. Writes release notes from the PR description
    4. Verifies deployment health
    5. Posts deployment status as a comment

  requires_tools:
    - github:merge_pr
    - github:create_release
    - github:add_comment
    - github:close_issue

  inputs:
    implementation_pr_url:
      type: string
      description: "URL to the approved PR"
      required: false
    fix_pr_url:
      type: string
      description: "URL to the fix PR (bug fix workflow)"
      required: false
    hotfix_pr_url:
      type: string
      description: "URL to the hotfix PR (fast-track workflow)"
      required: false

  outputs:
    deployment_status:
      type: string
      description: "Status of the deployment"
    release_url:
      type: string
      description: "URL to the created release"
    rollback_plan:
      type: string
      description: "Rollback plan for emergency deployments"

  prompt_template: |
    You are the deployment agent. Deploy the approved changes.

    PR: {implementation_pr_url}

    **MERGE POLICY (CRITICAL):**
    - Check the project's `require_human_merge_approval` setting in project_config.yaml
    - If set to `always`: DO NOT merge. Post a comment:
      `🚀 Deployment ready. PR requires human review before merge.`
      Then wait — do NOT run `gh pr merge`.
    - If set to `workflow-based`: Check the workflow step's approval_gates
    - If set to `never`: Proceed with merge (squash merge preferred)
    - When in doubt, DO NOT merge. Request human approval.

    Steps (when merge IS allowed):
    1. Merge the approved PR into the target branch
    2. Create a release with proper semantic versioning
    3. Write clear release notes
    4. Verify deployment health
    5. Post deployment status as a comment on the issue

    Steps (when merge is NOT allowed):
    1. Verify PR is ready (tests pass, reviews approved)
    2. Post deployment readiness comment on the issue
    3. Post `🚀 Deployment ready. PR requires human review before merge.`
    4. Do NOT run any merge command

  validation:
    required_outputs: ["deployment_status"]
