apiVersion: "nexus-core/v1"
kind: "Agent"
metadata:
  name: "Design"
  description: "Creates technical design proposals for feature requests"
  author: "Nexus Core Team"
  version: "0.1.0"

spec:
  # Agent type - determines which tasks this agent can handle
  # Types: triage | design | debug | developer | reviewer | docs | summarizer | escalation
  # When a task is assigned to "design", this agent will pick it up
  agent_type: "design"
  
  # Agent behavior configuration
  timeout_seconds: 600
  max_retries: 2
  
  purpose: |
    For feature requests, this agent:
    1. Reads the feature description
    2. Uses AI to create a technical design document
    3. Creates a new branch
    4. Commits the design doc
    5. Opens a PR for review
    6. Links back to original issue
    
  requires_tools:
    - github:get_issue
    - github:create_branch
    - github:create_file
    - github:create_pr
    - github:add_comment
    - ai:completion
  
  inputs:
    issue_url:
      type: string
      description: "URL to feature request issue"
      required: true
    scope:
      type: enum
      values: ["small", "medium", "large"]
      description: "Estimated feature scope"
      default: "medium"
  
  outputs:
    design_pr_url:
      type: string
      description: "URL of created design PR"
    estimated_effort:
      type: string
      description: "Rough effort estimate (e.g., '2-3 days')"
    next_steps:
      type: array
      items: string
      description: "Suggested implementation steps"
  
  ai_instructions: |
    Create a technical design document for this feature request:
    
    Feature: {feature_title}
    Description: {feature_description}
    Scope: {scope}
    
    Generate a MARKDOWN design doc with sections:
    
    ## Overview
    2-3 paragraphs explaining the feature and benefits
    
    ## Goals and Non-Goals
    Explicit scope boundaries
    
    ## Architecture & Implementation Approach
    How would this integrate with Nexus Core?
    What components need changes?
    
    ## API/Integration Points
    Code examples of how users would use this feature
    
    ## Data Models
    Any new data structures needed?
    
    ## Testing Strategy
    How should this be tested?
    
    ## Effort Estimate
    Small (< 1 day) | Medium (1-3 days) | Large (> 3 days)
    
    ## Migration & Backwards Compatibility
    Does this break existing workflows?
  
  example:
    input:
      issue_url: "https://github.com/Ghabs95/nexus-core/issues/28"
      scope: "large"
    expected_output:
      design_pr_url: "https://github.com/Ghabs95/nexus-core/pull/47"
      estimated_effort: "3-5 days"
      next_steps:
        - "Implement storage adapter interface"
        - "Add PostgreSQL provider"
        - "Add integration tests"
        - "Update documentation with examples"
