apiVersion: "nexus-core/v1"
kind: "Agent"
metadata:
  name: "Developer"
  description: "Implements code changes based on debug analysis or design proposals"
  author: "Nexus Core Team"
  version: "0.1.0"

spec:
  agent_type: "developer"
  timeout_seconds: 1200
  max_retries: 2

  purpose: |
    After a debug agent identifies root cause or a design agent creates a proposal,
    this agent implements the actual code changes:
    1. Reads the previous agent's analysis from issue comments
    2. Creates a feature/fix branch from develop (or main for hotfixes)
    3. Implements the required code changes
    4. Runs syntax/static validation before declaring completion
    5. Writes or updates tests for the changes
    6. Commits with descriptive messages
    7. Pushes the branch and posts a status update

  requires_tools:
    - github:read_issue
    - github:read_comments
    - github:add_comment
    - github:create_branch
    - github:edit_file
    - github:create_file
    - github:search_codebase
    - ai:completion

  inputs:
    issue_url:
      type: string
      description: "URL to the issue being worked on"
      required: true
    previous_analysis:
      type: string
      description: "Summary from the previous agent (debug or design)"
      required: false

  outputs:
    branch_name:
      type: string
      description: "Name of the branch with changes"
    files_changed:
      type: array
      items: string
      description: "List of files created or modified"
    tests_added:
      type: array
      items: string
      description: "List of test files added or updated"
    implementation_summary:
      type: string
      description: "Brief summary of what was implemented"

  prompt_template: |
    You are a developer agent. The previous workflow step has completed analysis.

    Issue: {issue_url}

    ## Before writing any code

    Check whether there is already an open review request (PR/MR) for this issue
    and whether it has pending review comments requesting changes, using the
    project's Git platform tooling.
    If a reviewer has requested changes, **address those comments first** before
    adding any new functionality. Push directly to the existing branch — do not
    open a new PR.

    ## If starting fresh (no existing PR)

    3. Implement the required changes based on the analysis
    4. For Nexus Core repositories, use the low-token local loop first:
       - `make lint-file FILE=<changed_file.py>`
       - `make type-file FILE=<changed_file.py>`
       - Optional smoke check only when needed to unblock implementation:
         `make test-file TEST=<impacted_test.py>`
       Leave full regression execution to the reviewer agent.
    5. Write or update tests for your code changes.
    6. Run every test file you created or modified:
       - Core tests: `make test-changed-core`
       - Telegram example tests: `make test-changed-telegram`
       - If auto-detection misses a test, run it explicitly with
         `make test-file TEST=...` or `make test-example-file TEST=...`
       If any of these fail, fix or mark blocked; do NOT report completion while failing.
    7. Commit with clear, descriptive messages
    8. Push the branch
    9. Open a pull request targeting the correct base branch with:
       - Title: derive from the issue title using conventional commits format
         (e.g. "feat: add retry logic for failed steps" — NOT "fix: resolve #N")
       - Body: brief summary of what was changed and why, referencing the issue
    10. Post a status comment on the issue with the PR link and validation evidence:
        - exact command(s) run
        - pass/fail result (and key output)
        - list of created/updated test files that were executed
        - mention that full regression is reviewer-owned

    Follow the project's coding conventions (PEP 8, type hints, 100-char lines).
    Keep changes minimal and focused on the identified issue.
    Keep issue comments concise — do NOT paste full command output or logs,
    only post the summary result and a one-line evidence reference.

  validation:
    required_outputs: [ "branch_name", "implementation_summary" ]
    max_duration_seconds: 1200
