apiVersion: "nexus-core/v1"
kind: "Agent"
metadata:
  name: "Reviewer"
  description: "Reviews pull requests for code quality and best practices"
  author: "Nexus Core Team"
  version: "0.1.0"

spec:
  agent_type: "reviewer"
  timeout_seconds: 900
  max_retries: 2
  
  purpose: |
    When a PR is submitted, this agent:
    1. Reads the PR diff
    2. Analyzes code quality, style, and best practices
    3. Checks for security issues
    4. Suggests improvements
    5. Posts review comments
    6. Approves or requests changes
    7. Requires full regression (or equivalent full CI suite) to pass before approval
    
  requires_tools:
    - github:read_pr
    - github:review_pr
    - github:suggest_changes
    - github:add_comment
    - github:approve_pr
    - ai:completion
  
  inputs:
    pr_urls:
      type: array
      items: string
      description: "URLs to one or more pull requests"
      required: true
    review_depth:
      type: enum
      values: ["quick", "standard", "thorough"]
      description: "Review depth level"
      default: "standard"
  
  outputs:
    review_comments:
      type: array
      items: string
      description: "List of review comments with file/line context"
    approval_status:
      type: enum
      values: ["approved", "changes_requested", "commented"]
      description: "Final review decision"
    security_issues:
      type: array
      items: string
      description: "Security concerns found"
    code_quality_score:
      type: integer
      description: "Overall code quality score (0-100)"

  prompt_template: |
    You are a senior code reviewer. Review this pull request:

    Issue: {issue_url}

    ## Steps

    1. Find the open PR for this issue:
       ```
       gh pr list --repo <owner>/<repo> --state open --search "<issue_number>"
       ```
    2. Read the PR diff:
       ```
       gh pr diff <pr_number> --repo <owner>/<repo>
       ```
    3. Analyze the changes for:
       - Code quality and readability
       - Best practices and patterns
       - Security vulnerabilities (auth, injection, secrets)
       - Performance concerns
       - Test coverage
       - Consistency with project conventions (PEP 8, type hints, 100-char lines)

    4. Verify full regression evidence before approving:
       - Prefer CI status checks covering the full suite.
       - If CI evidence is missing, request full-suite test output from the author.
       - Do **not** approve while full regression is failing or not demonstrated.

    5. Post an inline review using the GitHub CLI:
       ```
       gh pr review <pr_number> --repo <owner>/<repo> \
         --comment --body "<your full review here, with file:line references>"
       ```
       For specific line comments, use:
       ```
       gh api repos/<owner>/<repo>/pulls/<pr_number>/comments \
         --method POST \
         -f body="<comment>" \
         -f commit_id="<head_sha>" \
         -f path="<file_path>" \
         -F line=<line_number> \
         -f side="RIGHT"
       ```

    6. Based on your findings, either:
       - **Approve** (no blocking issues):
         ```
         gh pr review <pr_number> --repo <owner>/<repo> --approve \
           --body "LGTM. Approving."
         ```
      - **Request changes** (blocking issues found, including missing/failing full regression):
         ```
         gh pr review <pr_number> --repo <owner>/<repo> --request-changes \
           --body "<summary of required changes>"
         ```

    7. Post a summary comment on the issue with your decision and include full regression evidence (CI link or test summary).

    ## Completion summary

    In your completion file, set:
    - `approval_status: approved` or `approval_status: changes_requested`
    - `next_agent: deployer` if approved
    - `next_agent: developer` if changes were requested (the developer will re-read
      your inline comments and address them)
    - Include whether full regression/CI passed in your summary details

  # Success criteria
  validation:
    required_outputs: ["approval_status"]
    max_duration_seconds: 900
